#!/usr/bin/python

import os
import sys
import subprocess

def getpnm():
  PIDNAME = str(sys.argv[1])
  return PIDNAME

try:
    pidlist = str((str(subprocess.check_output(["pidof",getpnm()])).lstrip("b'").rstrip("'n\\"))).split(' ')
    for pid in pidlist:
        os.system(f'kill {pid}')
    exit(0)
except subprocess.CalledProcessError:
    print('This process doesn''t exist or is not running.')
    exit(1)
except IndexError:
    print('Please type the process'' name as the first argument.')
    exit(1)
